# xpath
login_url = "https://www.instagram.com/accounts/login/"
username = "//input[@name='username']"
password = "//input[@name='password']"
not_now_button = "//button[@class='GAMXX']"
search_url = "https://www.instagram.com/{}/"
following = "//a[@href='/{}/following/']/span"
followers = "//a[@href='/{}/followers/']/span"
get_id = "//a[@class='FPmhX notranslate  _0imsa ']"
direct_user = "//button[@class='fAR91 sqdOP  L3NKy _4pI4F   _8A5w5    ']"
send_direct = "//button[@class='sqdOP yWX7d    y3zKF     ']"
progress_bar = "//li[@class='wo9IH QN7kB ']"

# text
login_successfuly = "login successfuly"
user_found = "User found"
user_not_found = "User not found"
problem = "There was a problem running the program\nPlease check your internet"
please_wait = "following : {} "+"\nstart get data please wait ... "
elements_found = "This {} elements was found"
list_complete = "List complete"
private_page = "this page is private"
id_file = "The ID file is ready"